---

- hosts: ubuntu
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: install bind9
    apt:
      name=bind9
      state=latest
    when:
      ansible_os_family == "Debian"
