---

- hosts: rhel
  become: yes
  tasks:
  -  name: install java
     command: yum install java-1.8.0-openjdk -y
  -  name: download ES
     command: wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.2-x86_64.rpm
  -  name: install ES
     command: yum install elasticsearch-7.3.2-x86_64.rpm -y
  -  name: download Kibana
     command: wget https://artifacts.elastic.co/downloads/kibana/kibana-7.3.2-x86_64.rpm
  -  name: install Kibana
     command: yum install kibana-7.3.2-x86_64.rpm -y
  -  name: download logstash
     command: wget https://artifacts.elastic.co/downloads/logstash/logstash-7.3.2.rpm
  -  name: install logstash
     command: yum install logstash-7.3.2.rpm -y
     when:
        ansible_os_family == "RedHat"
