---

- hosts: ubuntu
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: install nginx
    apt:
      name=nginx
      state=latest
    when:
      ansible_os_family == "Debian"
