---

- hosts: rhel
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: install repo
    command: yum install https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm -y 
  - name: install agent
    command: yum install zabbix-agent -y
  - name: copy config  
    template:
     src: /etc/ansible/templates/zabbix_agentd.conf
     dest: /etc/zabbix/zabbix_agentd.conf
     mode: 775

  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started

- hosts: ubuntu
  become: true
  become_method: sudo
  become_user: root

  tasks:
  - name: install agent
    command: apt install zabbix-agent -y
  - name: copy config  
    template:
     src: /etc/ansible/templates/zabbix_agentd.conf
     dest: /etc/zabbix/zabbix_agentd.conf
     mode: 775

  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
